name: Build Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout

    - name: Set up Java
      uses: actions/setup-java
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Build and create zip
      run: |
        ant clean
        ant buildReleaseUpdate

    - name: Create Release
      id: create_release
      uses: actions/create-release
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
          tag_name: Release2
          release_name: Release ver8.571
          body: |
            Release notes and description here.
  
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/reelease.zip
          asset_name: reelease.zip
          asset_content_type: application/zip
