name: Build Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Build and create zip
      run: |
        ant clean
        ant buildReleaseUpdate

    - name: Upload release artifact
      id: create_release
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: dist/reelease.zip
